### Register ( δημιουργία admin χρήστη)
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "admin@beauty.com",
  "name": "Admin User",
  "password": "admin321"
}


###Login (σύνδεση χρήστη)
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@beauty.com",
  "password": "admin321"

}